/*
 * ApproveAPISwagger
 *
 * The simple API to request a user's approval on anything via email + sms.
 *
 * OpenAPI spec version: 1.0.1
 * Contact: dev@approveapi.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AnswerMetadata {
    #[serde(rename = "ip_address")]
    pub ip_address: Option<String>,
    #[serde(rename = "browser")]
    pub browser: Option<String>,
    #[serde(rename = "operating_system")]
    pub operating_system: Option<String>,
}

impl AnswerMetadata {
    pub fn new() -> AnswerMetadata {
        AnswerMetadata {
            ip_address: None,
            browser: None,
            operating_system: None,
        }
    }
}
