/*
 * ApproveAPISwagger
 *
 * The simple API to request a user's approval on anything via email + sms.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@approveapi.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PromptStatus {
    /// Whether the prompt has been answered or not.
    #[serde(rename = "is_answered")]
    pub is_answered: bool,
    /// Whether the prompt can still be answered.
    #[serde(rename = "is_expired")]
    pub is_expired: bool,
}

impl PromptStatus {
    pub fn new(is_answered: bool, is_expired: bool) -> PromptStatus {
        PromptStatus {
            is_answered: is_answered,
            is_expired: is_expired,
        }
    }
}
