/*
 * ApproveAPISwagger
 *
 * The simple API to request a user's approval on anything via email + sms.
 *
 * OpenAPI spec version: 1.0.1
 * Contact: dev@approveapi.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PromptMetadata {
    /// The physical location, like Oakland, CA, of the action.
    #[serde(rename = "location")]
    pub location: Option<String>,
    /// The date/time of the action.
    #[serde(rename = "time")]
    pub time: Option<String>,
    /// The IP address of the computer initiating the action.
    #[serde(rename = "ip_address")]
    pub ip_address: Option<String>,
    /// The web browser initiating the action, i.e. Chrome.
    #[serde(rename = "browser")]
    pub browser: Option<String>,
    /// The operating system initiating the action, i.e. Mac OS X.
    #[serde(rename = "operating_system")]
    pub operating_system: Option<String>,
}

impl PromptMetadata {
    pub fn new() -> PromptMetadata {
        PromptMetadata {
            location: None,
            time: None,
            ip_address: None,
            browser: None,
            operating_system: None,
        }
    }
}
