/*
 * ApproveAPISwagger
 *
 * The simple API to request a user's approval on anything via email + sms.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@approveapi.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PromptAnswer {
    /// The unix timestamp when the user answered the prompt.
    #[serde(rename = "time")]
    pub time: f32,
    /// The user's answer to whether or not they approve this prompt.
    #[serde(rename = "result")]
    pub result: bool,
    #[serde(rename = "metadata")]
    pub metadata: Option<::models::AnswerMetadata>,
}

impl PromptAnswer {
    pub fn new(time: f32, result: bool) -> PromptAnswer {
        PromptAnswer {
            time: time,
            result: result,
            metadata: None,
        }
    }
}
